from datetime import date
from app import app, db
from models import User, Tent, Visit

if __name__ == '__main__':
    with app.app_context():
        print("Clearing database...")
        User.query.delete()
        Tent.query.delete()
        Visit.query.delete()

        print("Starting seed...")

        print("Seeding users...")
        #Seed Users
        u1 = User(username = 'amsfreeman', email= 'amy@mail.com', age= 30, password_hash='munich')
        u2 = User(username = 'jesspapa', email='jess@mail.com', age = 35, password_hash='berlin')
        u3 = User(username = 'bowski', email='jon@mail.com', age= 37, password_hash='cologne')
        u4 = User(username = 'markc', email='mark@mail.com', age=30, password_hash='stuttgart')
        u5 = User(username = 'niamh', email='niamh@mail.com', age=33, password_hash='dresden')
        u6 = User(username = 'mkhobrecht', email='mk@mail.com', age = 28, password_hash='leipzig')
        u7 = User(username = 'katzbird', email='marc@mail.com', age = 25, password_hash='vienna')
        u8 = User(username = 'megawatt', email='megan@mail.com', age = 30, password_hash = 'bonn')
        u9 = User(username = 'bonbongiraffe', email='frankie@mail.com', age = 26, password_hash = 'hamburg')
        u10 = User(username = 'thereallisk', email = 'nolan@mail.com', age = 30, password_hash = 'frankfurt')

        users = [u1, u2, u3, u4, u5, u6, u7, u8, u9, u10]
        db.session.add_all(users)
        db.session.commit()

        print("Seeding tents...")
        t1 = Tent(name = "Armbrustschützenzelt", capacity = "7460", first_year = "1895", beer_sold = "Paulaner", image = "./static/assets/images/tent-images/tent1.jpg", star_image = "./static/assets/images/star-images/star-tent1.jpg", details = "This tent’s name means crossbow tent, and sure enough the German Crossbow Championships have taken place here since 1935. Guests to the tent won’t notice this though, as the crossbow events take place in a tent extension. Here one can also see traditional costume groups, and the whipcrackers performing. Visitors here include shooting groups, regulars, and locals of Munich. As in many tents, the band has a large repotaire, from classic music to new Oktoberfest hits. The tent’s host comes from a brewery family, but only Munich beer is allowed at Oktoberfest, so it is Paulaner served here, rather than his family beer.")
        t2 = Tent(name = "Augustiner-Festhalle", capacity= "8566", first_year= "1903", beer_sold = "Augustiner", image = "./static/assets/images/tent-images/tent2.jpg", star_image = "./static/assets/images/star-images/star-tent2.jpg", details="This tent’s beer is stored in wooden barrels, which results in better taste and less carbon dioxide. People who visit this tent tend to be regulars and Munich locals. As in most tents, the band plays more traditional Munich and Bavarian style music until the evening, when more modern hits and festival music become the norm. The food is supplied by the tent’s butcher shop, and has diverse options. Make sure to appreciate the Augustiner tower, back since 2010!")
        t3 = Tent(name = "Bräurosl", capacity = "8250", first_year = "1901", beer_sold = "Hacker-Pschorr", image = "./static/assets/images/tent-images/tent3.jpg", star_image = "./static/assets/images/star-images/star-tent3.jpg", details = "This tent has had a new look since 2022, but still maintains manly of the old traditions. It’s the tallest tent, with a top ridge of 15 meters. Visitors at this tent include regulars, families, and the LGBTQ community. The gay ‘Munich Lion’s Club’ has a special tradition on the first Sunday of Oktoberfest, where they invite people and wear leather, including both traditional and non-traditional costumes. As in most tents, Bavarian music is played during the day, and the party music gets going at night.")
        t4 = Tent(name = "Fischer-Vroni", capacity = "3872", first_year = "1904", beer_sold = "Augustiner", image = "./static/assets/images/tent-images/tent4.jpg", star_image = "./static/assets/images/star-images/star-tent4.jpg", details = "Fish on a stick is the speciality of this fish tent. Once upon a time there was a Fischer-Vroni, and this tent is still a family business! This tent is a mix of the traditional and modern. On the second Monday of Oktoberfest, the LGBTQ community has a meetup a Fischer-Vroni. A great party, if you can get there early enough to get a seat! A fun fact, on the last day of Oktoberfest, the last beer is served by men in dirndls (traditional Oktoberfest dress) and women in Lederhosen (tradition Oktoberfest short pants).")
        t5 = Tent(name = "Hacker-Festzelt", capacity = "9378", first_year = "1989", beer_sold = "Hacker-Pschorr", image = "./static/assets/images/tent-images/tent5.jpg", star_image = "./static/assets/images/star-images/star-tent5.jpg", details = "This tent’s ceiling has light blue fabric across it, leading to the feeling of being under an open sky. When the tent was rebuilt in 2016, a new 2,000-square-meter painting was added, with many scenes of life in Munich. Visitors to this tent range from young to old, and from regulars to those just there for the party. On the final night of Oktoberfest, this tent ends the night with sparklers, a special ending! The music includes rock ‘n’ roll, and the food is produced regionally.")
        t6 = Tent(name = "Hofbräu-Festzelt", capacity = "10040", first_year = "1952", beer_sold = "Staatliches Hofbräuhaus", image = "./static/assets/images/tent-images/tent6.jpg", star_image = "./static/assets/images/star-images/star-tent6.jpg", details = "The special feature here is the spinning angel named Aloisuis, who sits high in the tent and slowly rotates. It is also the only tent where one can stand in area in front of the band, or dance if you prefer! This tent, similar to the Hofbräu Haus in Munich near Marienplatz has an international flair. But don’t count out the locals, they love the party atmosphere! The menu is traditional, and has some cheaper lunch options.")
        t7 = Tent(name = "Käfer Wiesnschänke", capacity = "3264", first_year = "1972", beer_sold = "Paulaner", image = "./static/assets/images/tent-images/tent7.jpg", star_image = "./static/assets/images/star-images/star-tent7.jpg", details = "This tents gives a log cabin feel in the middle of Oktoberfest, which is different from other tents. The party also extends later into the night here, with the tent staying open till 12:30am (00:30). Visitors here include the famous, the FC Bayern Munich team, and the in-crowd. Only those with a reservation can get in! The food includes wonderful delicacies and first class dishes. A special souvenir can be bought here, a decorated coffee cup. Each there there is a new one to buy!")
        t8 = Tent(name = "Löwenbräu-Festzelt", capacity = "8478", first_year = "1910", beer_sold = "Löwenbräu", image = "./static/assets/images/tent-images/tent8.jpg", star_image = "./static/assets/images/star-images/star-tent8.jpg", details = "The unique feature here is the tower with a 1.5 meter tall Lion, which roars every minute! As one might guess from the mascot and blue-and-white color scheme, this tent has many visitors who are fans of TSV 1860 Munich. The players of the team sometimes stop by as well! Tourists are also common here, and it is easy to converse in English or Italian. The band’s cover of ‘Hey Jude’ is famous in this tent. This tent also prioritzes sustainability, making it a green choice!")
        t9 = Tent(name = "Marstall-Festzelt", capacity = "4368", first_year = "2014", beer_sold = "Spaten", image = "./static/assets/images/tent-images/tent9.jpg", star_image = "./static/assets/images/star-images/star-tent9.jpg", details = "This tent is the newest of the large Oktoberfest tents, only existing since 2014. The design was inspired by the connection of Oktoberfest to horses, and in fact ‘Marstall’ used to be the name of the Royal Riding School. Additionally, the first year of Oktoberfest in 1810, a horse race was held on the grounds. The horse imagry throughout the tent calls back to these connections! Visitors at this tent include many families, and no one stands on the benches before 4pm (16:00). The menu includes some veal specialities, along with classic Oktoberfest dishes.")
        t10 = Tent(name = "Ochsenbraterei", capacity = "7550", first_year = "1881", beer_sold = "Spaten", image = "./static/assets/images/tent-images/tent10.jpg", star_image = "./static/assets/images/star-images/star-tent10.jpg", details = "This tent’s unique speciality is oxen. Over 125 oxen are eaten during Oktoberfest. This is quiet different than the normal Oktoberfest menu of chicken! Visitors here tend include large numbers of regulars from Munich and fewer tourists. The brass band plays wonderful traditional music, as well as Oktoberfest hits in the evening! A piece of history for this tent is ‘toilet gate’ in 1892, where the beer license of the tent owner was revoked for not having toilets for guests! That resulted in this tent not reappearing at Oktoberfest until 1898.")
        t11 = Tent(name = "Schottenhamel-Festhalle", capacity = "9030", first_year = "1867", beer_sold = "Spaten", image = "./static/assets/images/tent-images/tent11.jpg", star_image = "./static/assets/images/star-images/star-tent11.jpg", details = "The traditional beer tapping to officially start Oktoberfest happens here at noon (12:00) on the opening day of Oktoberfest. Only after this tent taps the first keg can the other tents start serving beer. This tent is also the oldest tent, existing since 1867. Visitors often include the youth of Munich. As in most tents, the band plays more traditional music during the days, and the party hits at night. The music then turns romantic for the grand finale on the final Wiesn Sunday. A fun fact, Albert Einstein worked here when he was 17!")
        t12 = Tent(name = "Schützenfestzelt", capacity = "6500", first_year = "1926", beer_sold = "Löwenbräu", image = "./static/assets/images/tent-images/tent12.jpg", star_image = "./static/assets/images/star-images/star-tent12.jpg", details = "This tent boasts a traditional atmosphere and a beautiful balcony. The view from the famous south-side balcony allows one to see the Ferris Wheel, the Bavaria Statue, the sunset, and the people moving about. The yearly traditional Oktoberfest shoot, run by the Bavarian Sports Shooting Federation, takes place here. The tent’s traditional is long, as it is one of the oldest, exists since 1876. Visitors include nobility, Munich locals, and a few celebrities. The menu also includes a suckling pig in malt beer, the only tent that offers this!")
        t13 = Tent(name = "Weinzelt", capacity = "2535", first_year = "1984", beer_sold = "None, Wine instead of Oktoberfest Beer", image = "./static/assets/images/tent-images/tent13.jpg", star_image = "./static/assets/images/star-images/star-tent13.jpg", details = "This tent does not offer the traditional Oktoberfest Helles, but does offer a wheat beer. Take note, the beer is only on offer till 9pm (21:00)! Instead, the tent features wine, Processo, and stays up till 1am (01:00). The beautiful wood panelling also makes one feel like there are in a French vineyard. Visitors include regulars and some Munich celebrities. The menu is extensive and features great culinary diversity, from traditional Bavarian to Asian specialities.")
        t14 = Tent(name = "Winzerer Fähndl (Paulaner Festzelt)", capacity = "8398", first_year = "1895", beer_sold = "Paulaner", image = "./static/assets/images/tent-images/tent14.jpg", star_image = "./static/assets/images/star-images/star-tent14.jpg", details = "This tent features a tower outside with a giant spinning beer mug ‘Maßkrug’. It also features an extreme speed of beer pouring, up to 15 pours per tap per minute! That’s one beer every 4 seconds! Visitors include Munich regulars and VIPs such as FC Bayern Munich players. There are lots of great Munich classics on the menu, and the Paulaner Spezi drink is also available.")

        tents = [t1, t2, t3, t4, t5, t6, t7, t8, t9, t10, t11, t12, t13, t14]
        db.session.add_all(tents)
        db.session.commit()

        print("Seeding visits...")

        v1 = Visit(visit_rating = 3, date = date(2017,9,17), user_id = 4, tent_id = 4)
        v2 = Visit(visit_rating = 4, date = date(2018,9,20), user_id = 7, tent_id = 3)
        v3 = Visit(visit_rating = 5, date = date(2017,9,21), user_id = 9, tent_id = 10)
        v4 = Visit(visit_rating = 4, date = date(2017,10,2), user_id = 3, tent_id = 12)
        v5 = Visit(visit_rating = 3, date = date(2017,10,3), user_id = 1, tent_id = 1)
        v6 = Visit(visit_rating = 2, date = date(2018,10,3), user_id = 6, tent_id = 7)
        v7 = Visit(visit_rating = 1, date = date(2019,10,1), user_id = 10, tent_id = 11)
        v8 = Visit(visit_rating = 3, date = date(2019,9,20), user_id = 2, tent_id = 5)
        v9 = Visit(visit_rating = 4, date = date(2017,9,20), user_id = 5, tent_id = 2)
        v10 = Visit(visit_rating = 5, date = date(2022,10,2), user_id = 8, tent_id = 6)
        v11 = Visit(visit_rating = 3, date = date(2022,9,18), user_id = 9, tent_id = 14)
        v12 = Visit(visit_rating = 4, date = date(2022,9,25), user_id = 4, tent_id = 9)
        v13 = Visit(visit_rating = 1, date = date(2022,9,27), user_id = 7, tent_id = 8)
        v14 = Visit(visit_rating = 4, date = date(2017,9,30), user_id = 1, tent_id = 13)
        v15 = Visit(visit_rating = 5, date = date(2018,10,3), user_id = 6, tent_id = 4)
        v16 = Visit(visit_rating = 3, date = date(2019,10,2), user_id = 2, tent_id = 3)
        v17 = Visit(visit_rating = 4, date = date(2018,9,24), user_id = 8, tent_id = 10)
        v18 = Visit(visit_rating = 3, date = date(2017,9,20), user_id = 3, tent_id = 12)
        v19 = Visit(visit_rating = 2, date = date(2017,9,21), user_id = 5, tent_id = 1)
        v20 = Visit(visit_rating = 1, date = date(2017,9,24), user_id = 10, tent_id = 7)
        v21 = Visit(visit_rating = 5, date = date(2017,9,28), user_id = 3, tent_id = 11)
        v22 = Visit(visit_rating = 4, date = date(2022,9,27), user_id = 9, tent_id = 5)
        v23 = Visit(visit_rating = 2, date = date(2022,9,30), user_id = 7, tent_id = 2)
        v24 = Visit(visit_rating = 5, date = date(2017,9,25), user_id = 1, tent_id = 6)
        v25 = Visit(visit_rating = 2, date = date(2017,9,30), user_id = 8, tent_id = 14)
        v26 = Visit(visit_rating = 1, date = date(2018,9,26), user_id = 2, tent_id = 9)
        v27 = Visit(visit_rating = 3, date = date(2016,9,27), user_id = 4, tent_id = 8)
        v28 = Visit(visit_rating = 4, date = date(2019,9,25), user_id = 5, tent_id = 13)
        v29 = Visit(visit_rating = 5, date = date(2018,10,1), user_id = 6, tent_id = 4)
        v30 = Visit(visit_rating = 2, date = date(2018,9,18), user_id = 10, tent_id = 3)
        v31 = Visit(visit_rating = 5, date = date(2017,9,25), user_id = 8, tent_id = 10)
        v32 = Visit(visit_rating = 3, date = date(2018,9,25), user_id = 1, tent_id = 12)
        v33 = Visit(visit_rating = 4, date = date(2017,9,16), user_id = 5, tent_id = 1)
        v34 = Visit(visit_rating = 1, date = date(2018,9,22), user_id = 6, tent_id = 7)
        v35 = Visit(visit_rating = 1, date = date(2019,9,21), user_id = 9, tent_id = 11)
        v36 = Visit(visit_rating = 2, date = date(2022,9,17), user_id = 4, tent_id = 5)
        v37 = Visit(visit_rating = 5, date = date(2017,9,19), user_id = 7, tent_id = 2)
        v38 = Visit(visit_rating = 3, date = date(2019,9,21), user_id = 2, tent_id = 6)
        v39 = Visit(visit_rating = 2, date = date(2018,10,7), user_id = 10, tent_id = 14)
        v40 = Visit(visit_rating = 2, date = date(2017,10,3), user_id = 3, tent_id = 9)
        v41 = Visit(visit_rating = 2, date = date(2018,10,3), user_id = 2, tent_id = 8)
        v42 = Visit(visit_rating = 1, date = date(2019,10,2), user_id = 9, tent_id = 12)
        v43 = Visit(visit_rating = 5, date = date(2017,9,18), user_id = 5, tent_id = 4)
        v44 = Visit(visit_rating = 4, date = date(2018,10,1), user_id = 8, tent_id = 3)
        v45 = Visit(visit_rating = 3, date = date(2019,9,22), user_id = 1, tent_id = 10)
        v46 = Visit(visit_rating = 4, date = date(2018,9,24), user_id = 6, tent_id = 12)
        v47 = Visit(visit_rating = 5, date = date(2017,9,19), user_id = 7, tent_id = 1)
        v48 = Visit(visit_rating = 1, date = date(2017,9,20), user_id = 3, tent_id = 7)
        v49 = Visit(visit_rating = 1, date = date(2017,10,1), user_id = 4, tent_id = 11)
        v50 = Visit(visit_rating = 5, date = date(2018,10,3), user_id = 10, tent_id = 5)
        v51 = Visit(visit_rating = 4, date = date(2022,10,2), user_id = 6, tent_id = 2)
        v52 = Visit(visit_rating = 3, date = date(2022,9,20), user_id = 2, tent_id = 6)
        v53 = Visit(visit_rating = 2, date = date(2017,9,25), user_id = 7, tent_id = 14)
        v54 = Visit(visit_rating = 1, date = date(2018,10,2), user_id = 8, tent_id = 9)
        v55 = Visit(visit_rating = 2, date = date(2017,9,27), user_id = 4, tent_id = 8)
        v56 = Visit(visit_rating = 3, date = date(2022,9,27), user_id = 5, tent_id = 13)
        v57 = Visit(visit_rating = 4, date = date(2018,10,1), user_id = 3, tent_id = 4)
        v58 = Visit(visit_rating = 5, date = date(2022,9,27), user_id = 10, tent_id = 3)
        v59 = Visit(visit_rating = 1, date = date(2017,9,16), user_id = 1, tent_id = 10)
        v60 = Visit(visit_rating = 5, date = date(2019,9,22), user_id = 9, tent_id = 12)
        v61 = Visit(visit_rating = 2, date = date(2022,10,3), user_id = 7, tent_id = 1)
        v62 = Visit(visit_rating = 2, date = date(2017,9,24), user_id = 6, tent_id = 7)
        v63 = Visit(visit_rating = 1, date = date(2018,9,22), user_id = 4, tent_id = 11)
        v64 = Visit(visit_rating = 4, date = date(2018,10,5), user_id = 1, tent_id = 5)
        v65 = Visit(visit_rating = 2, date = date(2018,9,22), user_id = 2, tent_id = 2)
        v66 = Visit(visit_rating = 1, date = date(2022,9,29), user_id = 5, tent_id = 6)
        v67 = Visit(visit_rating = 5, date = date(2018,10,4), user_id = 10, tent_id = 14)
        v68 = Visit(visit_rating = 5, date = date(2017,9,26), user_id = 3, tent_id = 9)
        v69 = Visit(visit_rating = 3, date = date(2017,9,20), user_id = 8, tent_id = 8)
        v70 = Visit(visit_rating = 4, date = date(2018,10,6), user_id = 9, tent_id = 13)
        v71 = Visit(visit_rating = 2, date = date(2022,10,3), user_id = 9, tent_id = 4)
        v72 = Visit(visit_rating = 2, date = date(2017,9,24), user_id = 2, tent_id = 3)
        v73 = Visit(visit_rating = 1, date = date(2018,9,22), user_id = 5, tent_id = 10)
        v74 = Visit(visit_rating = 4, date = date(2018,10,5), user_id = 1, tent_id = 12)
        v75 = Visit(visit_rating = 2, date = date(2018,9,22), user_id = 3, tent_id = 1)
        v76 = Visit(visit_rating = 1, date = date(2022,9,29), user_id = 10, tent_id = 7)
        v77 = Visit(visit_rating = 5, date = date(2018,10,4), user_id = 4, tent_id = 11)
        v78 = Visit(visit_rating = 5, date = date(2017,9,26), user_id = 6, tent_id = 5)
        v79 = Visit(visit_rating = 3, date = date(2017,9,20), user_id = 7, tent_id = 2)
        v80 = Visit(visit_rating = 4, date = date(2018,10,6), user_id = 8, tent_id = 6)
        v81 = Visit(visit_rating = 1, date = date(2019,10,3), user_id = 5, tent_id = 14)
        v82 = Visit(visit_rating = 4, date = date(2018,9,26), user_id = 7, tent_id = 9)
        v83 = Visit(visit_rating = 2, date = date(2017,9,17), user_id = 4, tent_id = 8)
        v84 = Visit(visit_rating = 3, date = date(2017,9,17), user_id = 8, tent_id = 13)
        v85 = Visit(visit_rating = 3, date = date(2017,9,21), user_id = 2, tent_id = 4)
        v86 = Visit(visit_rating = 5, date = date(2018,9,25), user_id = 9, tent_id = 3)
        v87 = Visit(visit_rating = 2, date = date(2018,10,6), user_id = 10, tent_id = 10)
        v88 = Visit(visit_rating = 1, date = date(2017,10,3), user_id = 6, tent_id = 12)
        v89 = Visit(visit_rating = 1, date = date(2019,10,5), user_id = 1, tent_id = 1)
        v90 = Visit(visit_rating = 5, date = date(2018,10,7), user_id = 3, tent_id = 7)
        v91 = Visit(visit_rating = 3, date = date(2018,10,3), user_id = 1, tent_id = 11)
        v92 = Visit(visit_rating = 3, date = date(2017,9,22), user_id = 9, tent_id = 5)
        v93 = Visit(visit_rating = 4, date = date(2018,9,29), user_id = 7, tent_id = 2)
        v94 = Visit(visit_rating = 1, date = date(2022,9,21), user_id = 2, tent_id = 6)
        v95 = Visit(visit_rating = 2, date = date(2022,9,27), user_id = 10, tent_id = 14)
        v96 = Visit(visit_rating = 5, date = date(2018,10,1), user_id = 6, tent_id = 9)
        v97 = Visit(visit_rating = 3, date = date(2019,10,2), user_id = 4, tent_id = 8)
        v98 = Visit(visit_rating = 4, date = date(2018,10,4), user_id = 5, tent_id = 13)
        v99 = Visit(visit_rating = 2, date = date(2018,10,5), user_id = 3, tent_id = 4)
        v100 = Visit(visit_rating = 2, date = date(2017,9,23), user_id = 8, tent_id = 3)
        v101 = Visit(visit_rating = 1, date = date(2017,10,3), user_id = 3, tent_id = 10)
        v102 = Visit(visit_rating = 5, date = date(2018,9,25), user_id = 6, tent_id = 12)
        v103 = Visit(visit_rating = 2, date = date(2019,10,2), user_id = 9, tent_id = 1)
        v104 = Visit(visit_rating = 4, date = date(2017,9,29), user_id = 8, tent_id = 7)
        v105 = Visit(visit_rating = 3, date = date(2019,9,30), user_id = 7, tent_id = 11)
        v106 = Visit(visit_rating = 3, date = date(2019,10,5), user_id = 5, tent_id = 5)
        v107 = Visit(visit_rating = 4, date = date(2019,10,6), user_id = 4, tent_id = 2)
        v108 = Visit(visit_rating = 5, date = date(2017,9,26), user_id = 10, tent_id = 6)
        v109 = Visit(visit_rating = 2, date = date(2018,9,29), user_id = 2, tent_id = 14)
        v110 = Visit(visit_rating = 1, date = date(2018,9,29), user_id = 1, tent_id = 9)
        v111 = Visit(visit_rating = 5, date = date(2019,10,1), user_id = 4, tent_id = 8)
        v112 = Visit(visit_rating = 3, date = date(2018,10,4), user_id = 5, tent_id = 13)
        v113 = Visit(visit_rating = 2, date = date(2019,9,24), user_id = 9, tent_id = 4)
        v114 = Visit(visit_rating = 2, date = date(2017,9,30), user_id = 1, tent_id = 3)
        v115 = Visit(visit_rating = 4, date = date(2022,9,30), user_id = 2, tent_id = 10)
        v116 = Visit(visit_rating = 5, date = date(2017,10,2), user_id = 10, tent_id = 12)
        v117 = Visit(visit_rating = 3, date = date(2018,10,3), user_id = 7, tent_id = 1)
        v118 = Visit(visit_rating = 2, date = date(2019,9,28), user_id = 3, tent_id = 7)
        v119 = Visit(visit_rating = 4, date = date(2018,10,5), user_id = 6, tent_id = 11)
        v120 = Visit(visit_rating = 5, date = date(2019,10,6), user_id = 8, tent_id = 5)
        v121 = Visit(visit_rating = 1, date = date(2017,10,3), user_id = 8, tent_id = 2)
        v122 = Visit(visit_rating = 3, date = date(2017,10,1), user_id = 7, tent_id = 6)
        v123 = Visit(visit_rating = 2, date = date(2022,9,27), user_id = 6, tent_id = 14)
        v124 = Visit(visit_rating = 5, date = date(2022,10,3), user_id = 2, tent_id = 9)
        v125 = Visit(visit_rating = 5, date = date(2017,9,23), user_id = 3, tent_id = 8)
        v126 = Visit(visit_rating = 1, date = date(2017,10,3), user_id = 10, tent_id = 13)
        v127 = Visit(visit_rating = 4, date = date(2022,10,3), user_id = 5, tent_id = 4)
        v128 = Visit(visit_rating = 4, date = date(2018,10,5), user_id = 1, tent_id = 3)
        v129 = Visit(visit_rating = 1, date = date(2019,10,6), user_id = 9, tent_id = 10)
        v130 = Visit(visit_rating = 3, date = date(2017,9,24), user_id = 4, tent_id = 12)
        v131 = Visit(visit_rating = 2, date = date(2019,9,30), user_id = 6, tent_id = 1)
        v132 = Visit(visit_rating = 4, date = date(2019,9,27), user_id = 5, tent_id = 7)
        v133 = Visit(visit_rating = 4, date = date(2019,9,29), user_id = 9, tent_id = 11)
        v134 = Visit(visit_rating = 5, date = date(2022,10,1), user_id = 7, tent_id = 5)
        v135 = Visit(visit_rating = 1, date = date(2022,9,17), user_id = 3, tent_id = 2)
        v136 = Visit(visit_rating = 2, date = date(2022,10,3), user_id = 1, tent_id = 6)
        v137 = Visit(visit_rating = 3, date = date(2022,10,3), user_id = 10, tent_id = 14)
        v138 = Visit(visit_rating = 5, date = date(2019,10,6), user_id = 2, tent_id = 9)
        v139 = Visit(visit_rating = 2, date = date(2017,10,2), user_id = 8, tent_id = 8)
        v140 = Visit(visit_rating = 5, date = date(2019,9,28), user_id = 4, tent_id = 13)

        visits = [
                v1, v2, v3, v4, v5, v6, v7, v8, v9, v10, 
                v11, v12, v13, v14, v15, v16, v17, v18, v19, v20, 
                v21, v22, v23, v24, v25, v26, v27, v28, v29, v30,
                v31, v32, v33, v34, v35, v36, v37, v38, v39, v40,
                v41, v42, v43, v44, v45, v46, v47, v48, v49, v50,
                v51, v52, v53, v54, v55, v56, v57, v58, v59, v60,
                v61, v62, v63, v64, v65, v66, v67, v68, v69, v70,
                v71, v72, v73, v74, v75, v76, v77, v78, v79, v80,
                v81, v82, v83, v84, v85, v86, v87, v88, v89, v90,
                v91, v92, v93, v94, v95, v96, v97, v98, v99, v100,
                v101, v102, v103, v104, v105, v106, v107, v108, v109, v110,
                v111, v112, v113, v114, v115, v116, v117, v118, v119, v120,
                v121, v122, v123, v124, v125, v126, v127, v128, v129, v130,
                v131, v132, v133, v134, v135, v136, v137, v138, v139, v140,
                ]
        db.session.add_all(visits)
        db.session.commit()

        print("Done seeding!")