"""re-adding visits table

Revision ID: 0eaf826943e7
Revises: 5d807f722cab
Create Date: 2023-08-21 11:29:48.315403

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0eaf826943e7'
down_revision = '5d807f722cab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('visits', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tent_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint('fk_visits_visit_id_visits', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_visits_tent_id_tents'), 'tents', ['tent_id'], ['id'])
        batch_op.drop_column('visit_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('visits', schema=None) as batch_op:
        batch_op.add_column(sa.Column('visit_id', sa.INTEGER(), nullable=True))
        batch_op.drop_constraint(batch_op.f('fk_visits_tent_id_tents'), type_='foreignkey')
        batch_op.create_foreign_key('fk_visits_visit_id_visits', 'visits', ['visit_id'], ['id'])
        batch_op.drop_column('tent_id')

    # ### end Alembic commands ###
