"""added star image to tents table

Revision ID: 9af548eb09cf
Revises: f88e510c60e0
Create Date: 2023-08-25 17:56:37.192090

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9af548eb09cf'
down_revision = 'f88e510c60e0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('star_image', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tents', schema=None) as batch_op:
        batch_op.drop_column('star_image')

    # ### end Alembic commands ###
